#!/bin/bash

# Ticket Booking System - Quick Start Guide
echo "🎟️  Ticket Booking System - Quick Start"
echo "========================================"
echo ""
echo "Step 1️⃣  - Setup MySQL Database"
echo "Run this command in MySQL terminal or MySQL Workbench:"
echo ""
echo "mysql -u root -p < database.sql"
echo ""
echo "Or manually execute:"
echo "  1. Open MySQL Command Line"
echo "  2. Run: mysql -u root -p"
echo "  3. Enter your MySQL password"
echo "  4. Copy and paste contents of database.sql"
echo ""
echo "========================================"
echo ""
echo "Step 2️⃣  - Start Backend Server"
echo "cd backend"
echo "npm start"
echo ""
echo "You should see: ✅ MySQL Connected Successfully!"
echo "               🚀 Server Running on http://localhost:5000"
echo ""
echo "========================================"
echo ""
echo "Step 3️⃣  - Start Frontend (Open NEW Terminal)"
echo "cd frontend"
echo "npm start"
echo ""
echo "App opens at: http://localhost:3000"
echo ""
echo "========================================"
echo ""
echo "✨ Your Ticket Booking System is ready!"
echo ""
